# Build React app
FROM node:16-alpine as build-step
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY client/package.json client/yarn.lock ./
COPY ./client/src ./src
COPY ./client/public ./public
COPY client/yarn.lock ./yarn.lock
RUN yarn install
COPY client/ ./
RUN yarn run build

# Serve with Nginx
FROM nginx:stable-alpine
COPY --from=build-step /app/build /usr/share/nginx/html
COPY ./client/deployment/nginx.default.conf /etc/nginx/conf.d/default.conf
