version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: ./app/Dockerfile.api
    image: invoice-matching-api
    container_name: api
    ports:
      - "5001:5000"
    networks:
      - invoice-matching
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=development
      - PYTHONPATH=/app
    volumes:
      - .:/app
    depends_on:
      - db
    command: gunicorn -b 0.0.0.0:5000 wsgi:app

  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile.client
    image: invoice-matching-client
    container_name: react-client
    ports:
      - "3000:80"
    networks:
      - invoice-matching
    depends_on:
      - api

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: invoice_matching
      MYSQL_USER: user
      MYSQL_PASSWORD: secret123
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - invoice-matching

networks:
  invoice-matching:
    driver: bridge

volumes:
  mysql_data:
