FROM python:3.9

WORKDIR /app
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt
ENV FLASK_ENV production
ENV FLASK_APP=wsgi.py
COPY . /app

EXPOSE 5000
CMD ["flask", "run", "--host=0.0.0.0"]