FROM python:3.9

WORKDIR /app
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt
ENV FLASK_ENV=development
ENV FLASK_APP=wsgi.py
COPY . /app

EXPOSE 5001

CMD gunicorn wsgi:app --bind 0.0.0.0:$PORT
