FROM python:3.9

WORKDIR /app
COPY ./requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r ./requirements.txt
ENV FLASK_ENV production
COPY . /app

EXPOSE 5000
CMD ["gunicorn", "-b", ":5000", "app:app"]