"""Fixed conflict between Invoice and Delivery models

Revision ID: 6e6af53a5aa4
Revises: 9fc297ccedeb
Create Date: 2025-02-01 22:36:57.322079

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6e6af53a5aa4'
down_revision = '9fc297ccedeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_number', sa.String(length=255), nullable=False))
        batch_op.drop_column('line_item_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_item_number', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('delivery_number')

    # ### end Alembic commands ###
