"""Enhance invoice, delivery, and line item models

Revision ID: 9fc297ccedeb
Revises: c2009423ed87
Create Date: 2025-01-30 14:34:28.066941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc297ccedeb'
down_revision = 'c2009423ed87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('delivery_date', sa.Date(), nullable=False))

    with op.batch_alter_table('delivery_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_item_number', sa.Integer(), nullable=True))

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('invoice_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('customer_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('currency', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint(None, ['invoice_number'])

    with op.batch_alter_table('invoice_line_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_item_number', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('subtotal', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice_line_item', schema=None) as batch_op:
        batch_op.drop_column('subtotal')
        batch_op.drop_column('description')
        batch_op.drop_column('line_item_number')

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('currency')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('customer_name')
        batch_op.drop_column('invoice_date')
        batch_op.drop_column('invoice_number')

    with op.batch_alter_table('delivery_line_item', schema=None) as batch_op:
        batch_op.drop_column('line_item_number')

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('supplier_name')

    # ### end Alembic commands ###
